baseURL = 'https://alis-lang.github.io/'
languageCode = 'en-us'
title = 'Alis Language'
theme = 'hextra'
[module.imports]
	path = "github.com/imfing/hextra"
[menu]
	[[menu.main]]
		weight = 1
		name = 'Docs'
		pageRef = '/docs'
	[[menu.main]]
		weight = 2
		name = 'About'
		pageRef = '/about'
	[[menu.main]]
		weight = 3
		name = 'Source'
		url = 'https://github.com/alis-lang'
	[[menu.main]]
		weight = 4
		name = 'Search'
		[menu.main.params]
			type = 'search'

[params]
	[params.navbar]
		displayTitle = true
		displayLogo = false
	[params.footer]
		displayCopyright = true
		displayPoweredBy = false
	[params.page]
		width = "wide"
	[params.flexsearch]
		index = "content"
